# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_beekeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=140)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'hive_thumb')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
