# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.IntegerField(default=0),
        ),
    ]
