# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20161024_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('event', 'email')]),
        ),
    ]
