# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20161024_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([]),
        ),
    ]
