# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20161024_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beekeeper',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
