# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20161024_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(default='Physics', max_length=25),
            preserve_default=False,
        ),
    ]
