# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20161119_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Hive')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 7, 57, 24, 375597)),
        ),
    ]
