# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_auto_20161119_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 10, 44, 3, 955746)),
        ),
    ]
