# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_auto_20161119_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[(b'DEPT', b'Department (e.g. Physics)'), (b'BIOLOGY', b'Biology'), (b'EXTERNAL', b'External group/organisation'), (b'OTHER', b'Other')], default=b'OTHER', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 10, 54, 20, 509016)),
        ),
    ]
