# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20161119_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 13, 10, 32, 68656)),
        ),
    ]
