# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-19 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_auto_20161119_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 19, 14, 10, 16, 633330)),
        ),
    ]
