# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_auto_20161119_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 16, 34, 28, 595345)),
        ),
    ]
