# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-08 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0027_auto_20161203_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stats',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 10, 41, 41, 16371)),
        ),
    ]
