# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-08 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_auto_20161208_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photos',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 11, 3, 24, 953644)),
        ),
    ]
