# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-08 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_auto_20161208_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playlist',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 14, 43, 39, 558239)),
        ),
    ]
