# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-18 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_auto_20170114_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_reg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 6, 2, 51, 836160)),
        ),
    ]
