# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_auto_20170128_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.GroupType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 28, 16, 57, 32, 298695)),
        ),
    ]
