# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_auto_20170219_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 1, 9, 7, 41, 382041)),
        ),
    ]
