# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0035_auto_20170128_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='type',
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 28, 16, 59, 4, 389278)),
        ),
        migrations.DeleteModel(
            name='GroupType',
        ),
    ]
