# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-24 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0035_auto_20170301_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signupURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 11, 25, 56, 69552)),
        ),
    ]
