# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0036_auto_20170524_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 6, 2, 59, 696932)),
        ),
    ]
