# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0037_auto_20170616_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='song',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 12, 3, 11, 832258)),
        ),
    ]
