# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0038_auto_20170807_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 12, 34, 22, 61641)),
        ),
    ]
