# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0044_auto_20170807_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 17, 39, 7, 36557)),
        ),
    ]
