# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-08 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0046_auto_20170808_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='beekeeper',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 2, 8, 1, 321586)),
        ),
    ]
