# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-20 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0054_auto_20170919_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 7, 24, 32, 362800)),
        ),
    ]
