# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-25 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0055_auto_20170920_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 12, 16, 28, 338468)),
        ),
    ]
