# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-25 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0056_auto_20170925_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 16, 34, 17, 77710)),
        ),
    ]
