# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-03 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0057_auto_20170925_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 9, 35, 46, 755566)),
        ),
    ]
