# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-09 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0058_auto_20171003_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 15, 48, 27, 738932)),
        ),
    ]
