# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0059_auto_20171009_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 11, 52, 41, 812973)),
        ),
    ]
