# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hello', '0040_auto_20170807_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('github_link', models.URLField()),
                ('azure_link', models.URLField()),
                ('video_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'module_thumb')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Beekeeper')),
            ],
        ),
    ]
