# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170807_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
