# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_module_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='azure_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
