# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20170807_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='cocalc_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
