# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_element_cocalc_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Element'),
        ),
    ]
