# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_element_next_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='next_lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_lesson', to='resources.Element'),
        ),
    ]
