# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20170809_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='next_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.Element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='prev_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Element'),
        ),
    ]
