# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20170809_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='recommended',
            field=models.ManyToManyField(blank=True, null=True, related_name='_element_recommended_+', to='resources.Element'),
        ),
    ]
