# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_element_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
