# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_module_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
