# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_module_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tagline',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
